# Generated by Django 5.1.4 on 2024-12-24 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("agent_settings", "0001_initial"),
        ("hebo_organizations", "0001_initial"),
        ("versions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentsetting",
            name="organization",
            field=models.ForeignKey(
                help_text="Organization this agent belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_settings",
                to="hebo_organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="agentsetting",
            name="version",
            field=models.OneToOneField(
                help_text="The version these settings belong to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_settings",
                to="versions.version",
            ),
        ),
        migrations.AddField(
            model_name="tool",
            name="agent_setting",
            field=models.ForeignKey(
                help_text="The agent setting this tool belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tools",
                to="agent_settings.agentsetting",
            ),
        ),
        migrations.AddIndex(
            model_name="agentsetting",
            index=models.Index(
                fields=["version"], name="agent_setti_version_52354a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tool",
            index=models.Index(
                fields=["agent_setting"], name="agent_setti_agent_s_bd4675_idx"
            ),
        ),
    ]
