# Generated by Django 5.1.4 on 2025-02-10 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("agent_settings", "0001_initial"),
        ("hebo_organizations", "0001_initial"),
        ("versions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentsetting",
            name="organization",
            field=models.ForeignKey(
                help_text="Organization this agent belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_settings",
                to="hebo_organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="agentsetting",
            name="version",
            field=models.OneToOneField(
                help_text="The version these settings belong to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_settings",
                to="versions.version",
            ),
        ),
        migrations.AddField(
            model_name="llmadapter",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this adapter belongs to (null if default)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="llm_adapters",
                to="hebo_organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="agentsetting",
            name="condense_llm",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"model_type": "chat"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="condense_llm_settings",
                to="agent_settings.llmadapter",
            ),
        ),
        migrations.AddField(
            model_name="agentsetting",
            name="core_llm",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"model_type": "chat"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="core_llm_settings",
                to="agent_settings.llmadapter",
            ),
        ),
        migrations.AddField(
            model_name="agentsetting",
            name="embeddings",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"model_type": "embedding"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="embedding_settings",
                to="agent_settings.llmadapter",
            ),
        ),
        migrations.AddField(
            model_name="agentsetting",
            name="vision_llm",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"model_type": "chat"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vision_llm_settings",
                to="agent_settings.llmadapter",
            ),
        ),
        migrations.AddField(
            model_name="tool",
            name="agent_setting",
            field=models.ForeignKey(
                help_text="The agent setting this tool belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tools",
                to="agent_settings.agentsetting",
            ),
        ),
        migrations.AddIndex(
            model_name="llmadapter",
            index=models.Index(
                fields=["organization", "model_type"],
                name="agent_setti_organiz_9934f3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="llmadapter",
            index=models.Index(
                fields=["is_default", "model_type"],
                name="agent_setti_is_defa_6a1c30_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="llmadapter",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("is_default", True), ("organization__isnull", True)),
                    models.Q(("is_default", False), ("organization__isnull", False)),
                    _connector="OR",
                ),
                name="organization_xor_default",
            ),
        ),
        migrations.AddIndex(
            model_name="agentsetting",
            index=models.Index(
                fields=["version"], name="agent_setti_version_52354a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="agentsetting",
            constraint=models.UniqueConstraint(
                fields=("version",), name="unique_version_settings"
            ),
        ),
        migrations.AddIndex(
            model_name="tool",
            index=models.Index(
                fields=["agent_setting"], name="agent_setti_agent_s_bd4675_idx"
            ),
        ),
    ]
