# Generated by Django 5.1.4 on 2025-02-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_settings", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmadapter",
            name="name",
            field=models.CharField(
                help_text="Name/ID of the model from the provider", max_length=150
            ),
        ),
    ]
