# Generated by Django 5.1.4 on 2025-01-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_settings", "0002_initial"),
        ("hebo_organizations", "0004_alter_organization_id"),
        ("versions", "0002_remove_agent_unique_agent_name_per_organization_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="name",
            field=models.CharField(default="tool", max_length=200),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="agentsetting",
            constraint=models.UniqueConstraint(
                fields=("version",), name="unique_version_settings"
            ),
        ),
    ]
