# Generated by Django 5.1.4 on 2025-01-24 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_settings", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentsetting",
            name="vision_llm",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"model_type": "chat"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vision_llm_settings",
                to="agent_settings.llmadapter",
            ),
        ),
        migrations.AlterField(
            model_name="llmadapter",
            name="model_type",
            field=models.CharField(
                choices=[("chat", "Chat"), ("embedding", "Embedding")],
                default="chat",
                help_text="Type of model (chat, embedding, or vision)",
                max_length=20,
            ),
        ),
    ]
