# Generated by Django 5.1.4 on 2025-03-17 04:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent_settings", "0003_alter_llmadapter_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentsetting",
            name="include_last_24h_history",
            field=models.BooleanField(default=False),
        ),
    ]
