# Generated by Django 5.1.4 on 2025-02-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_settings", "0003_alter_agentsetting_vision_llm_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmadapter",
            name="aws_access_key_id",
            field=models.CharField(
                blank=True,
                help_text="AWS Access Key ID (required for Bedrock)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="llmadapter",
            name="aws_secret_access_key",
            field=models.CharField(
                blank=True,
                help_text="AWS Secret Access Key (required for Bedrock)",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="llmadapter",
            name="api_key",
            field=models.CharField(
                blank=True,
                help_text="API key, service account JSON, or other authentication credentials",
                max_length=2000,
            ),
        ),
        migrations.AlterField(
            model_name="llmadapter",
            name="provider",
            field=models.CharField(
                choices=[
                    ("anthropic", "Anthropic"),
                    ("openai", "OpenAI"),
                    ("azure", "Azure"),
                    ("bedrock", "AWS Bedrock"),
                    ("vertex-ai", "Vertex AI"),
                    ("voyage", "Voyage"),
                ],
                help_text="AI provider for this model",
                max_length=20,
            ),
        ),
    ]
