# Generated by Django 5.1.4 on 2025-01-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_settings", "0003_tool_name_agentsetting_unique_version_settings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tool",
            name="sql_query",
        ),
        migrations.AddField(
            model_name="tool",
            name="query",
            field=models.TextField(
                blank=True,
                help_text="Query to execute for Data Source type tools",
                null=True,
            ),
        ),
    ]
