# Generated by Django 5.1.4 on 2025-03-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent_settings", "0004_agentsetting_include_last_24h_history"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tool",
            old_name="openapi_url",
            new_name="url",
        ),
        migrations.RemoveField(
            model_name="tool",
            name="db_connection_string",
        ),
        migrations.RemoveField(
            model_name="tool",
            name="output_template",
        ),
        migrations.RemoveField(
            model_name="tool",
            name="query",
        ),
        migrations.RemoveField(
            model_name="tool",
            name="tool_type",
        ),
        migrations.AddField(
            model_name="tool",
            name="input_schema",
            field=models.JSONField(
                default=dict, help_text="JSON schema for the tool's input parameters"
            ),
        ),
    ]
