# Generated by Django 5.1.4 on 2025-01-03 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0012_2_8"),
        ("hebo_organizations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="stripe_customer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hebo_organization",
                to="djstripe.customer",
            ),
        ),
        migrations.AlterField(
            model_name="organizationinvitation",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hebo_organization_invitation",
                to="hebo_organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="organizationowner",
            name="organization_user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hebo_organization_owner",
                to="hebo_organizations.organizationuser",
            ),
        ),
        migrations.AlterField(
            model_name="organizationuser",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hebo_organization_user",
                to="hebo_organizations.organization",
            ),
        ),
    ]
