# Generated by Django 5.1.4 on 2025-01-03 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hebo_organizations", "0002_alter_organization_stripe_customer_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hebo_organization_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
