# Generated by Django 5.1.4 on 2025-01-03 05:54

import hebo_organizations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hebo_organizations", "0003_alter_organizationuser_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="id",
            field=models.CharField(
                default=hebo_organizations.models.generate_org_id,
                editable=False,
                max_length=40,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
