services:
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - backend
  #     - proxy

  # backend:
  #   build:
  #     context: ..
  #     dockerfile: docker/backend.Dockerfile
  #   ports:
  #     - "8000:8000"
  #   env_file:
  #     - ./backend/.env
  #   depends_on:
  #     - db
  #     - redis

  # proxy:
  #   build:
  #     context: ..
  #     dockerfile: docker/proxy.Dockerfile
  #   ports:
  #     - "8001:8001"
  #   env_file:
  #     - ./proxy/.env
  #   depends_on:
  #     - redis

  db:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: hebo
      POSTGRES_PASSWORD: hebo
      POSTGRES_DB: hebo
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

# Add volumes definition at the root level
volumes:
  postgres_data:
