# Generated by Django 5.1.4 on 2025-01-06 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="slug",
        ),
    ]
