# Generated by Django 5.1.4 on 2025-02-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={
                "ordering": ["parent__id", "position", "-updated_at"],
                "verbose_name": "Page",
                "verbose_name_plural": "Pages",
            },
        ),
        migrations.AddField(
            model_name="page",
            name="position",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                help_text="Position of the page within its parent level",
            ),
        ),
    ]
