# Generated by Django 5.1.4 on 2025-03-06 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="part",
            name="unique_part_identifier_per_page",
        ),
        migrations.RemoveIndex(
            model_name="part",
            name="knowledge_p_page_id_4c3442_idx",
        ),
        migrations.RemoveField(
            model_name="page",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="part",
            name="identifier",
        ),
        migrations.RemoveField(
            model_name="part",
            name="is_valid",
        ),
        migrations.AlterField(
            model_name="vectorstore",
            name="part",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vectors",
                to="knowledge.part",
            ),
        ),
        migrations.AddIndex(
            model_name="part",
            index=models.Index(
                fields=["page", "content_type"], name="knowledge_p_page_id_114f60_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="part",
            index=models.Index(
                fields=["page", "content_hash"], name="knowledge_p_page_id_05e4c5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="part",
            constraint=models.UniqueConstraint(
                fields=("page", "start_line"), name="unique_part_per_page"
            ),
        ),
    ]
