# Generated by Django 5.1.4 on 2025-03-13 03:48

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0003_remove_vectorstore_unique_vector_per_part_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="vectorstore",
            name="vector_index",
        ),
        migrations.RemoveField(
            model_name="vectorstore",
            name="vector",
        ),
        migrations.AddField(
            model_name="vectorstore",
            name="vector_1024",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=1024, null=True
            ),
        ),
        migrations.AddField(
            model_name="vectorstore",
            name="vector_1536",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=1536, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="vectorstore",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=["vector_1536"],
                m=16,
                name="vector_1536_index",
                opclasses=["vector_cosine_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="vectorstore",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=["vector_1024"],
                m=16,
                name="vector_1024_index",
                opclasses=["vector_cosine_ops"],
            ),
        ),
    ]
