# Generated by Django 5.1.4 on 2025-02-10 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hebo_organizations", "0001_initial"),
        ("versions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentSlug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Slug for accessing this agent", max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="agent",
            name="unique_agent_slug_per_organization",
        ),
        migrations.AlterField(
            model_name="agent",
            name="slug",
            field=models.SlugField(
                help_text="Primary slug of the agent", max_length=255
            ),
        ),
        migrations.AddConstraint(
            model_name="agent",
            constraint=models.UniqueConstraint(
                fields=("organization", "name", "created_at"),
                name="unique_agent_name_timestamp_per_organization",
            ),
        ),
        migrations.AddField(
            model_name="agentslug",
            name="agent",
            field=models.ForeignKey(
                help_text="The agent this slug belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slugs",
                to="versions.agent",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentslug",
            constraint=models.UniqueConstraint(
                fields=("agent", "slug"), name="unique_agent_slug_per_organization"
            ),
        ),
    ]
