# Generated by Django 5.1.4 on 2025-01-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hebo_organizations", "0004_alter_organization_id"),
        ("versions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="agent",
            name="unique_agent_name_per_organization",
        ),
        migrations.AddConstraint(
            model_name="agent",
            constraint=models.UniqueConstraint(
                fields=("organization", "name", "created_at"),
                name="unique_agent_name_timestamp_per_organization",
            ),
        ),
    ]
