# Generated by Django 5.1.4 on 2025-02-10 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("api_keys", "0001_initial"),
        ("hebo_organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="organization",
            field=models.ForeignKey(
                help_text="Organization this API key belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_keys",
                to="hebo_organizations.organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="apikey",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"),
                name="unique_api_key_name_per_organization",
            ),
        ),
    ]
