# Generated by Django 5.1.4 on 2025-02-10 06:54

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hebo_organizations", "0001_initial"),
        ("versions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Thread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_open",
                    models.BooleanField(
                        default=True, help_text="Whether the thread is open or closed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact_name",
                    models.CharField(
                        help_text="Randomly generated name for the contact",
                        max_length=100,
                    ),
                ),
                (
                    "contact_identifier",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization this thread belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threads",
                        to="hebo_organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("error", "Error"),
                            ("expired", "Expired"),
                        ],
                        default="created",
                        help_text="Current status of the run",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    models.ForeignKey(
                        help_text="The version this run belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="versions.version",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        help_text="The thread this run belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="threads.thread",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Summary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="The summarized content of the thread conversation"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "thread",
                    models.OneToOneField(
                        help_text="The thread this summary belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary",
                        to="threads.thread",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "summaries",
                "indexes": [
                    models.Index(
                        fields=["thread"], name="threads_sum_thread__b31641_idx"
                    ),
                    models.Index(
                        fields=["-updated_at"], name="threads_sum_updated_e28ce1_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "run_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("created", "Created"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("error", "Error"),
                            ("expired", "Expired"),
                        ],
                        help_text="The status of the run when this message was generated",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("ai", "AI"),
                            ("human", "Human"),
                            ("human_agent", "Human Agent"),
                            ("tool", "Tool Answer"),
                            ("comment", "Comment"),
                        ],
                        help_text="Type of the message sender",
                        max_length=20,
                    ),
                ),
                (
                    "content",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="List of content objects. Example: [{'type': 'text', 'text': 'Hello'}]",
                    ),
                ),
                (
                    "tool_call_id",
                    models.CharField(
                        blank=True,
                        help_text="The ID of the tool call this message is a response to",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        help_text="The thread this message belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="threads.thread",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["thread", "created_at"],
                        name="threads_mes_thread__f3e6a7_idx",
                    ),
                    models.Index(
                        fields=["message_type"], name="threads_mes_message_a63d8d_idx"
                    ),
                ],
            },
        ),
    ]
