# Generated by Django 5.1.4 on 2024-12-24 03:06

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hebo_organizations", "0001_initial"),
        ("versions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Thread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_open",
                    models.BooleanField(
                        default=True, help_text="Whether the thread is open or closed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "writing_status",
                    models.CharField(
                        choices=[
                            ("idle", "Idle"),
                            ("writing", "Writing"),
                            ("error", "Error"),
                        ],
                        default="idle",
                        help_text="Current writing status of the thread",
                        max_length=20,
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        help_text="Randomly generated name for the contact",
                        max_length=100,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization this thread belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threads",
                        to="hebo_organizations.organization",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        help_text="The version this thread belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threads",
                        to="versions.version",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Summary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="The summarized content of the thread conversation"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "thread",
                    models.OneToOneField(
                        help_text="The thread this summary belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary",
                        to="threads.thread",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "summaries",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("assistant", "Assistant"),
                            ("user", "User"),
                            ("tool", "Tool"),
                        ],
                        help_text="Type of the message sender",
                        max_length=20,
                    ),
                ),
                (
                    "content",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="List of content objects. Example: [{'type': 'text', 'text': 'Hello'}]",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        help_text="The thread this message belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="threads.thread",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="thread",
            index=models.Index(
                fields=["organization", "-updated_at"],
                name="threads_thr_organiz_b1bf60_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="thread",
            index=models.Index(
                fields=["version", "-updated_at"], name="threads_thr_version_3ed7f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="summary",
            index=models.Index(
                fields=["thread"], name="threads_sum_thread__b31641_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="summary",
            index=models.Index(
                fields=["-updated_at"], name="threads_sum_updated_e28ce1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["thread", "created_at"], name="threads_mes_thread__f3e6a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["message_type"], name="threads_mes_message_a63d8d_idx"
            ),
        ),
    ]
