# Generated by Django 5.1.4 on 2025-02-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("threads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="run_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("created", "Created"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("error", "Error"),
                    ("expired", "Expired"),
                ],
                help_text="The status of the run when this message was generated",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="tool_call_id",
            field=models.CharField(
                blank=True,
                help_text="The ID of the tool call this message is a response to",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("ai", "AI"),
                    ("human", "Human"),
                    ("human_agent", "Human Agent"),
                    ("tool", "Tool Answer"),
                    ("comment", "Comment"),
                ],
                help_text="Type of the message sender",
                max_length=20,
            ),
        ),
    ]
